<?php

function athulya_alters_init() {
 /* $path = current_path();
  //dsm($path);
  $path_alias = drupal_lookup_path('alias',$path);
  //dsm($path_alias);
  if ($path_alias == 'facilities') {
	  drupal_add_css(drupal_get_path('theme','athulya'). '/css/facilities.css');
  }
  if ($path_alias == 'about-us') {
	  drupal_add_css(drupal_get_path('theme','athulya'). '/css/about.css');
  }
  if ($path_alias == 'service-apartments') {
	  drupal_add_css(drupal_get_path('theme','athulya'). '/css/facilities.css');
  }
  if ($path_alias == 'contact-us') {
	  drupal_add_css(drupal_get_path('theme','athulya'). '/css/contact.css');
  }
  if ($path_alias == 'corporate-guest-house') {
	  drupal_add_css(drupal_get_path('theme','athulya'). '/css/corporate.css');
  }
  if ($path_alias == 'paying-guest') {
	  drupal_add_css(drupal_get_path('theme','athulya'). '/css/facilities.css');
  }*/
}

function athulya_alters_menu() {
  $items['hostel-detail/%/%'] = array(
    'title' => 'Room Detail',
    'page callback' => 'athulya_alters_room_detail',
	'page arguments' => array(1, 2),
    'access arguments' => array('access content'),
    'type' => MENU_SUGGESTED_ITEM,
  );

  return $items;
}

function athulya_alters_room_detail($hostel_nid, $sharing_type) {
	
	//dsm($hostel_nid);
	//dsm($sharing_type);
	$output = '<div class="row">
         <div class="col-md-4 heading1">
            <h2><center>2 Share room</center></h2>
         </div>
      </div>
      <div class="row margining20">
         <div class="col-md-12">
            <img src="/sites/all/themes/athulya/img/libiary3.jpg" class="img-responsive">
         </div>
      </div>
      <div class="container">
         <div class="row margining20">
            <div class="col-md-2 col-md-offset-6">
               <p><img src="/sites/all/themes/athulya/img/Room-Full.jpg">Full</p>
            </div>
            <div class="col-md-2">
               <p><img src="/sites/all/themes/athulya/img/Room-Available.jpg">2 Remaining</p>
            </div>
            <div class="col-md-2">
               <p><img src="/sites/all/themes/athulya/img/Room-1-Bed-Available.jpg">1 Remaining</p>
            </div>
         </div>
         ';
		 
		 $f_tree = taxonomy_get_tree(5);
		 
		 foreach ($f_tree as $tree) {
		  //dsm($tree);
		  $floor_id = $tree->tid;
		  
		  $query = db_query("SELECT node.title AS node_title, node.nid AS nid, node.created AS node_created
FROM 
{node} node
LEFT JOIN {field_data_field_tag_hostels} field_data_field_tag_hostels ON node.nid = field_data_field_tag_hostels.entity_id AND (field_data_field_tag_hostels.entity_type = 'node' AND field_data_field_tag_hostels.deleted = '0')
LEFT JOIN {field_data_field_room_sharing_type} field_data_field_room_sharing_type ON node.nid = field_data_field_room_sharing_type.entity_id AND (field_data_field_room_sharing_type.entity_type = 'node' AND field_data_field_room_sharing_type.deleted = '0')
LEFT JOIN {field_data_field_floor} field_data_field_floor ON node.nid = field_data_field_floor.entity_id AND (field_data_field_floor.entity_type = 'node' AND field_data_field_floor.deleted = '0')
LEFT OUTER JOIN {support_ticket} st ON st.nid = node.nid
WHERE (( (field_data_field_tag_hostels.field_tag_hostels_nid = '" . $hostel_nid . "' ) AND (field_data_field_room_sharing_type.field_room_sharing_type_tid = '" . $sharing_type . "' ) AND (field_data_field_floor.field_floor_tid = '" . $floor_id . "' ) )AND(( (node.status = '1') AND (node.type IN  ('room')) )))AND (st.nid IS NULL )");
		  $result = $query->fetchAll();
		  
          $output .=  '<div class="row margining20">
		  <div class="col-md-2 margining20 width10">
               <p>' . $tree->name . '</p>
            </div>
            <div class="col-md-8 well backcolor">';
			foreach ($result as $res) {
              $output .= '<div class="col-md-2">' . $res->node_title . '</div>';
			}   
           $output .= '</div>
         </div>';
		 
		}
        $output .= '
      </div>';
	return $output;
}


/**
 * Implements hook_block_info().
 */
function athulya_alters_block_info() {
  $blocks['our_clients'] = array(
    'info' => t('Our Clients'),
  );
  
  $blocks['sharing_types'] = array(
    'info' => t('Sharing Types'),
  );
  
  $blocks['hostel_eminities'] = array(
    'info' => t('Hostel Ameninties'),
  );
  
  $blocks['footer_social_media'] = array(
    'info' => t('Footer Social Media Icons'),
  );
  
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function athulya_alters_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'our_clients':
      $block['content'] = athulya_alters_our_clients();
      break;
	case 'sharing_types':
      $block['content'] = athulya_alters_sharing_types();
      break;
	case 'hostel_eminities':
      $block['content'] = athulya_alters_hostel_eminities();
      break;
	case 'footer_social_media':
      $block['content'] = athulya_alters_footer_social_media();
      break;
  }

  return $block;
}

function athulya_alters_our_clients() {
  $output = '<div class="container-fluid" style="background-image: url(sites/all/themes/athulya/img/dining_room.jpg);">
  <div class="row">
    <div class="span12">
           
                <div id="myCarousel" class="carousel slide copy">
                 
                <ol class="carousel-indicators">
                    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                    <li data-target="#myCarousel" data-slide-to="1"></li>
                    <li data-target="#myCarousel" data-slide-to="2"></li>
                </ol>
                 
                <!-- Carousel items -->
                <div class="carousel-inner">
                    
                <div class="item active">
                  <div class="row">
                       <center><h1 style="color:white;">OUR CLIENTS</h1></center>
                  <div class="col-md-4 ">
                    <div class="span3">
                       <center>
                          <img src="sites/all/themes/athulya/img/images.jpg"/>
                          <p class="padding-bottom">Rooms are well lit,Rooms are well lit,Rooms are well lit,Rooms are well lit,Rooms are well lit,Rooms are well lit,Rooms are well lit,Rooms are well lit,</p>
                          <h6 style="font-weight: bold;">AMIT</h6>
                        </center>
                    </div>
                 </div>
                   <div class="col-md-4 ">
                    <div class="span3">
                       <center>
                          <img src="sites/all/themes/athulya/img/images.jpg"/>
                          <p class="padding-bottom">Rooms are well lit,Rooms are well lit,Rooms are well lit,Rooms are well lit,Rooms are well lit,Rooms are well lit,Rooms are well lit,Rooms are well lit,</p>
                          <h6 style="font-weight: bold;">AMIT</h6>
                        </center>
                    </div>
                 </div>
                  <div class="col-md-4 ">
                    <div class="span3">
                       <center>
                          <img src="sites/all/themes/athulya/img/images.jpg"/>
                          <p class="padding-bottom">Rooms are well lit,Rooms are well lit,Rooms are well lit,Rooms are well lit,Rooms are well lit,Rooms are well lit,Rooms are well lit,Rooms are well lit,</p>
                          <h6 style="font-weight: bold;">AMIT</h6>
                        </center>
                    </div>
                 </div>
               </div><!--/row-fluid-->
            </div><!--/item-->
                 
                <div class="item">
                  <div class="row">
                   <center><h1 style="color:white;">OUR CLIENTS</h1></center>
                       <div class="col-md-4 ">
                        <div class="span3">
                           <center>
                              <img src="sites/all/themes/athulya/img/images.jpg"/>
                              <p class="padding-bottom">Rooms are well lit,Rooms are well lit,Rooms are well lit,Rooms are well lit,Rooms are well lit,Rooms are well lit,Rooms are well lit,Rooms are well lit,</p>
                              <h6 style="font-weight: bold;">AMIT</h6>
                            </center>
                        </div>
                 </div>
                 <div class="col-md-4 ">
                    <div class="span3">
                       <center>
                          <img src="sites/all/themes/athulya/img/images.jpg"/>
                          <p class="padding-bottom">Rooms are well lit,Rooms are well lit,Rooms are well lit,Rooms are well lit,Rooms are well lit,Rooms are well lit,Rooms are well lit,Rooms are well lit,</p>
                          <h6 style="font-weight: bold;">AMIT</h6>
                        </center>
                    </div>
                 </div>
                  <div class="col-md-4 ">
                    <div class="span3">
                       <center>
                          <img src="sites/all/themes/athulya/img/images.jpg"/>
                          <p class="padding-bottom">Rooms are well lit,Rooms are well lit,Rooms are well lit,Rooms are well lit,Rooms are well lit,Rooms are well lit,Rooms are well lit,Rooms are well lit,</p>
                          <h6 style="font-weight: bold;">AMIT</h6>
                        </center>
                    </div>
                 </div>
              </div><!--/row-fluid-->
            </div><!--/item-->
                 
                <div class="item">
                  <div class="row">
                   <center><h1 style="color:white;">OUR CLIENTS</h1></center>
                   <div class="col-md-4 ">
                    <div class="span3">
                       <center>
                          <img src="sites/all/themes/athulya/img/images.jpg"/>
                          <p class="padding-bottom">Rooms are well lit,Rooms are well lit,Rooms are well lit,Rooms are well lit,Rooms are well lit,Rooms are well lit,Rooms are well lit,Rooms are well lit,</p>
                          <h6 style="font-weight: bold;">AMIT</h6>
                        </center>
                    </div>
                 </div>
                   <div class="col-md-4 ">
                    <div class="span3">
                       <center>
                          <img src="sites/all/themes/athulya/img/images.jpg"/>
                          <p class="padding-bottom">Rooms are well lit,Rooms are well lit,Rooms are well lit,Rooms are well lit,Rooms are well lit,Rooms are well lit,Rooms are well lit,Rooms are well lit,</p>
                          <h6 style="font-weight: bold;">AMIT</h6>
                        </center>
                    </div>
                 </div>
                  <div class="col-md-4 ">
                    <div class="span3">
                       <center>
                          <img src="sites/all/themes/athulya/img/images.jpg"/>
                          <p class="padding-bottom">Rooms are well lit,Rooms are well lit,Rooms are well lit,Rooms are well lit,Rooms are well lit,Rooms are well lit,Rooms are well lit,Rooms are well lit,</p>
                          <h6 style="font-weight: bold;">AMIT</h6>
                        </center>
                    </div>
                 </div>
                </div><!--/row-fluid-->
              </div><!--/item-->
                 
          </div><!--/carousel-inner-->
                 
                <a class="left carousel-control" href="#myCarousel" data-slide="prev"><span class="glyphicon glyphicon-chevron-left"></span></a>
                <a class="right carousel-control" href="#myCarousel" data-slide="next"><span class="glyphicon glyphicon-chevron-right"></span></a>
                </div><!--/myCarousel-->
                 
           
    </div>
  </div>
</div>';
  return $output;
}

function athulya_alters_sharing_types() {
	//dsm(arg(1));
	$s_tree = taxonomy_get_tree(3);
	//dsm($s_tree);
	
	//total rooms with 2 sharing_types
	
	//select * from room where sharing type = 2 and hostel = 1
	
  $output = '<div class="container">
          <div class="row">';
  foreach ($s_tree as $tree) {
	  
	  /*$num_active_users = db_select('users', 'u')
							  ->fields('u')
							  ->condition('status', 1)
							  ->countQuery()
							  ->execute()
							  ->fetchField();*/
	  
	  $result = db_query("SELECT node.title AS node_title, node.nid AS nid, node.created AS node_created
FROM 
{node} node
LEFT JOIN {field_data_field_tag_hostels} field_data_field_tag_hostels ON node.nid = field_data_field_tag_hostels.entity_id AND (field_data_field_tag_hostels.entity_type = 'node' AND field_data_field_tag_hostels.deleted = '0')
LEFT JOIN {field_data_field_room_sharing_type} field_data_field_room_sharing_type ON node.nid = field_data_field_room_sharing_type.entity_id AND (field_data_field_room_sharing_type.entity_type = 'node' AND field_data_field_room_sharing_type.deleted = '0')
LEFT OUTER JOIN {support_ticket} st ON st.nid = node.nid
WHERE (( (field_data_field_tag_hostels.field_tag_hostels_nid = '" . arg(1) . "' ) AND (field_data_field_room_sharing_type.field_room_sharing_type_tid = '" . $tree->tid . "' ) )AND(( (node.status = '1') AND (node.type IN  ('room')) )))AND (st.nid IS NULL )");
$tot_res = $result->fetchAll();
	  
		  $output .= '
              <div class="col-md-4 sample">
                  <div class="carbox">
                      <a class="img-carbox" href="#">
                      <img src="https://1.bp.blogspot.com/-Bii3S69BdjQ/VtdOpIi4aoI/AAAAAAAABlk/F0z23Yr59f0/s640/cover.jpg" /></a>

                      <div class="carbox-content">
                          <h4 class="carbox-title">
                          <a href="/hostel-detail/' . arg(1) . '/' . $tree->name . '">' . $tree->name . '</a>
                          </h4>
                          <p class="">Rooms : ' . count($tot_res) . '</p>
                      </div>
                           
                  </div>
              </div>';
  }
  $output .= '</div>
</div>';
  return $output;
}

function athulya_alters_hostel_eminities() {
  $output = '<div class="row">
   <div class="col-md-12 text-center">
        <h3><b>AMENITIES</b></h3>
        <hr style="width:8%;border-color: black;">
    </div>
      <div class="row">
         <div class="container">
            <div class="col-md-10 col-md-offset-1">
              <p>lorem ispusm is simply dummy text of the printing and typesetting industry. Lorem ispum has been the industrys standard dummy text ever since the 1500s,when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
            </div>
          </div>
      </div>
</div>
  
  <div class="row" id="back">
    <div class="col-md-12 col-lg-offset-1">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-2">
            <div class="box">             
              <div class="icon">
              
                <div class="info">
                      <div class="image"><i class="fa fa-desktop"></i></div>
                      <h5 class="title">Desktop Friendly</h5>
                        <p>Beautiful,Standardized,Functional</p>
                </div>
            </div>
         </div> 
     </div>

     <div class="col-xs-12 col-sm-12 col-md-12 col-lg-2">
       <div class="box">             
          <div class="icon">
             <div class="info">
                <div class="image"><i class="fa fa-desktop"></i></div>
                <h5 class="title">Desktop Friendly</h5>
                <p>Beautiful,Standardized,Functional</p> 
            </div>
        </div>
      </div> 
    </div>
     <div class="col-xs-12 col-sm-12 col-md-12 col-lg-2">
        <div class="box">             
           <div class="icon">
              <div class="info">
                 <div class="image"><i class="fa fa-desktop"></i></div>
                 <h5 class="title">Desktop Friendly</h5>
                 <p>Beautiful,Standardized,Functional</p>
            </div>
         </div>
      </div> 
    </div>

     <div class="col-xs-12 col-sm-12 col-md-12 col-lg-2">
       <div class="box">             
         <div class="icon">
            <div class="info">
                <div class="image"><i class="fa fa-desktop"></i></div>
                <h5 class="title">Desktop Friendly</h5>
                <p>Beautiful,Standardized,Functional</p>
            </div>
        </div>
      </div> 
    </div>

     <div class="col-xs-12 col-sm-12 col-md-12 col-lg-2">
        <div class="box">             
          <div class="icon">
             <div class="info">
                <div class="image"><i class="fa fa-desktop"></i></div>
                <h5 class="title">Shared Spaces</h5>
                <p>Beautiful,Standardized,Functional</p>
            </div>
          </div>
      </div> 
    </div>
  </div>
 </div>
 </div>';
  return $output;
}
function athulya_alters_footer_social_media() {
	$output = '<div class="social-media">
                   <ul>
                      <li><i class="fa fa-facebook" aria-hidden="true"></i></li>
                      <li><i class="fa fa-twitter " aria-hidden="true"></i></li>
                      <li><i class="fa fa-linkedin" aria-hidden="true"></i></li> 
                  </ul>
               </div>';
	return $output;
}